### ISSUE TITLE
chained comparisons

### ISSUE THREAD

**Issue by rocky** [andrew-tavera/unpyc37#5]
This program

```
def chained_compare_a(protocol):
    if not 0 <= protocol <= 7:
        raise ValueError("pickle protocol must be <= %d" % 7)

def chained_compare_b(a, obj):
    if a:
        if -0x80000000 <= obj <= 0x7fffffff:
            return 5

def chained_compare_c(a, d):
    for i in len(d):
        if a == d[i] != 2:
            return 5

chained_compare_a(3)
try:
    chained_compare_a(8)
except ValueError:
    pass
chained_compare_b(True, 0x0)

chained_compare_c(3, [3])
```

when compiled and decompiled with unpyc37 gives: 

```
Traceback (most recent call last):
  File "unpyc37/unpyc3.py", line 2899, in <module>
    print(decompile(sys.argv[1]))
  File "unpyc37/unpyc3.py", line 1505, in __str__
    self.display(istr)
  File "unpyc37/unpyc3.py", line 1511, in display
    stmt.display(indent)
  File "unpyc37/unpyc3.py", line 1335, in display
    self.display_undecorated(indent)
  File "unpyc37/unpyc3.py", line 1361, in display_undecorated
    self.code.get_suite().display(indent + 1)
  File "unpyc37/unpyc3.py", line 433, in get_suite
    dec.run()
  File "unpyc37/unpyc3.py", line 1594, in run
    new_addr = method(*args)
  File "unpyc37/unpyc3.py", line 2620, in POP_JUMP_IF_FALSE
    return self.POP_JUMP_IF(addr, target, truthiness=False)
  File "unpyc37/unpyc3.py", line 2447, in POP_JUMP_IF
    c = c.chain(cond)
AttributeError: 'PyName' object has no attribute 'chain'
```

**Comment by rocky** [comment]
Similar is:

```python
digit = 1
if isinstance(digit, int) and 0 <= digit <= 9:
    pass
```
